// GENERIERT von scripts/gen-katalog.mjs – nicht von Hand ändern.
// Quelle: Übungskatalog.xlsx. Änderungen gehören in die Excel; der Build
// erzeugt diese Datei daraus neu (prebuild).
//
// haupt = Hauptspieler (zählt im Wochenkonto voll), neben = Nebenspieler
// (Anzeige als 1 indirekter Satz, Gesamtgewichtung 0,5), typ = Comp/Iso (entscheidet, in welchem Slot die Übung steht).

export const KONTEN = [
  "Brust",
  "Lat",
  "Oberer Rücken",
  "Vordere Schulter",
  "Seitliche Schulter",
  "Hintere Schulter",
  "Bizeps",
  "Trizeps",
  "Unterarme",
  "Quads",
  "Hams",
  "Glutes",
  "Abduktoren",
  "Waden",
  "Abs",
];

export const KATALOG = [
  { n: "Bank Dips (Brustbetont)", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "Dips (Brustbetont)", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "Kabel Fliegende", haupt: "Brust", neben: ["Vordere Schulter"], typ: "Iso" },
  { n: "Kabel Überzüge", haupt: "Brust", neben: ["Lat"], typ: "Iso" },
  { n: "KH Flachbankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "KH Fliegende", haupt: "Brust", neben: ["Vordere Schulter"], typ: "Iso" },
  { n: "KH Negativbankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "KH Schrägbankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "KH Überzüge", haupt: "Brust", neben: ["Lat"], typ: "Iso" },
  { n: "LH Flachbankdrücken", haupt: "Brust", neben: ["Trizeps", "Vordere Schulter"], typ: "Comp" },
  { n: "LH Flachbankdrücken, eng", haupt: "Brust", neben: ["Trizeps", "Vordere Schulter"], typ: "Comp" },
  { n: "LH Guillotine Bankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "LH Negativbankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "LH Schrägbankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "Multipresse Flachbankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "Multipresse Flachbankdrücken, eng", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "Multipresse Guillotine Bankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "Multipresse Negativbankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "Multipresse Schrägbankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "PlateLoaded Dips (Brustbetont)", haupt: "Brust", neben: ["Vordere Schulter"], typ: "Comp" },
  { n: "PlateLoaded Flachbankdrücken", haupt: "Brust", neben: ["Vordere Schulter"], typ: "Comp" },
  { n: "PlateLoaded Fliegende", haupt: "Brust", neben: ["Vordere Schulter"], typ: "Iso" },
  { n: "PlateLoaded Negativbankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "PlateLoaded Schrägbankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "Steck Dips (Brustbetont)", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "Steck Flachbankdrücken", haupt: "Brust", neben: ["Vordere Schulter", "Trizeps"], typ: "Comp" },
  { n: "Steck Fliegende", haupt: "Brust", neben: ["Vordere Schulter"], typ: "Iso" },
  { n: "Steck Schrägbankdrücken", haupt: "Brust", neben: ["Trizeps", "Vordere Schulter"], typ: "Comp" },
  { n: "Steck Überzüge", haupt: "Brust", neben: ["Lat"], typ: "Iso" },
  { n: "Kabel Rudern, eng, Hammergriff", haupt: "Lat", neben: ["Oberer Rücken", "Bizeps", "Hintere Schulter"], typ: "Comp" },
  { n: "Kabel Überzüge, weit (Lat-betont)", haupt: "Lat", neben: ["Brust"], typ: "Iso" },
  { n: "Kabel Überzüge, weit", haupt: "Lat", neben: ["Brust"], typ: "Comp" },
  { n: "KH Rudern", haupt: "Lat", neben: ["Oberer Rücken", "Bizeps", "Hintere Schulter"], typ: "Comp" },
  { n: "Klimmzug, eng, Hammergriff", haupt: "Lat", neben: ["Bizeps", "Oberer Rücken"], typ: "Comp" },
  { n: "Klimmzug, Obergriff", haupt: "Lat", neben: ["Oberer Rücken", "Bizeps"], typ: "Comp" },
  { n: "Klimmzug, Untergriff", haupt: "Lat", neben: ["Bizeps", "Oberer Rücken"], typ: "Comp" },
  { n: "Latziehen in den Nacken", haupt: "Lat", neben: ["Oberer Rücken", "Bizeps"], typ: "Comp" },
  { n: "Latziehen zur Brust", haupt: "Lat", neben: ["Bizeps", "Hintere Schulter", "Oberer Rücken"], typ: "Comp" },
  { n: "Latziehen, eng, neutral", haupt: "Lat", neben: ["Bizeps"], typ: "Comp" },
  { n: "Plate Loaded High Rows", haupt: "Lat", neben: ["Bizeps"], typ: "Comp" },
  { n: "LH Überzüge, weit", haupt: "Lat", neben: ["Brust"], typ: "Comp" },
  { n: "LH Überzüge, weit (Lat-betont)", haupt: "Lat", neben: ["Brust"], typ: "Iso" },
  { n: "Kabel Face Pulls", haupt: "Oberer Rücken", neben: ["Hintere Schulter"], typ: "Iso" },
  { n: "Kabel Rudern, weit, Obergriff", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps", "Hintere Schulter"], typ: "Comp" },
  { n: "Kabel Shruggs", haupt: "Oberer Rücken", neben: [], typ: "Iso" },
  { n: "KH Rudern, Obergriff", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps"], typ: "Comp" },
  { n: "KH Shruggs", haupt: "Oberer Rücken", neben: [], typ: "Iso" },
  { n: "KH Trap3Raise", haupt: "Oberer Rücken", neben: ["Hintere Schulter"], typ: "Iso" },
  { n: "LH Rudern, Obergriff", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps", "Hintere Schulter"], typ: "Comp" },
  { n: "LH Rudern, Untergriff", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps"], typ: "Comp" },
  { n: "LH Shruggs", haupt: "Oberer Rücken", neben: [], typ: "Iso" },
  { n: "LH T-Bar Rudern", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps", "Hintere Schulter"], typ: "Comp" },
  { n: "LH Seal Rows", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps", "Hintere Schulter"], typ: "Comp" },
  { n: "Multipresse Rudern, Untergriff", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps"], typ: "Comp" },
  { n: "Multipresse Rudern, Obergriff", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps", "Hintere Schulter"], typ: "Comp" },
  { n: "Multipresse Shruggs", haupt: "Oberer Rücken", neben: [], typ: "Iso" },
  { n: "PlateLoaded Rudern", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps", "Hintere Schulter"], typ: "Comp" },
  { n: "PlateLoaded T-Bar Rudern", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps", "Hintere Schulter"], typ: "Comp" },
  { n: "Plate Loaded Low Rows", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps", "Hintere Schulter"], typ: "Comp" },
  { n: "Powell Raise", haupt: "Oberer Rücken", neben: ["Hintere Schulter"], typ: "Iso" },
  { n: "Rudern mit Seil zum Hals", haupt: "Oberer Rücken", neben: ["Hintere Schulter"], typ: "Iso" },
  { n: "Steck Rudern, Obergriff", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps", "Hintere Schulter"], typ: "Comp" },
  { n: "Steck Rudern, Untergriff", haupt: "Oberer Rücken", neben: ["Lat", "Bizeps"], typ: "Comp" },
  { n: "Y-Raise", haupt: "Oberer Rücken", neben: ["Hintere Schulter"], typ: "Iso" },
  { n: "Kabel Frontheben", haupt: "Vordere Schulter", neben: ["Seitliche Schulter"], typ: "Iso" },
  { n: "KH Arnoldpresse", haupt: "Vordere Schulter", neben: ["Seitliche Schulter", "Trizeps"], typ: "Comp" },
  { n: "KH Frontdrücken", haupt: "Vordere Schulter", neben: ["Seitliche Schulter", "Trizeps"], typ: "Comp" },
  { n: "KH Frontheben", haupt: "Vordere Schulter", neben: ["Seitliche Schulter"], typ: "Iso" },
  { n: "LH Frontdrücken", haupt: "Vordere Schulter", neben: ["Seitliche Schulter", "Trizeps"], typ: "Comp" },
  { n: "LH Frontheben", haupt: "Vordere Schulter", neben: ["Seitliche Schulter"], typ: "Iso" },
  { n: "Multipresse Frontdrücken", haupt: "Vordere Schulter", neben: ["Seitliche Schulter", "Trizeps"], typ: "Comp" },
  { n: "PlateLoaded Frontdrücken", haupt: "Vordere Schulter", neben: ["Seitliche Schulter", "Trizeps"], typ: "Comp" },
  { n: "Steck Frontdrücken", haupt: "Vordere Schulter", neben: ["Seitliche Schulter", "Trizeps"], typ: "Comp" },
  { n: "SZ Frontheben", haupt: "Vordere Schulter", neben: ["Seitliche Schulter"], typ: "Iso" },
  { n: "Kabel Aufrechtes Rudern", haupt: "Seitliche Schulter", neben: ["Oberer Rücken", "Bizeps"], typ: "Comp" },
  { n: "Kabel Seitheben", haupt: "Seitliche Schulter", neben: ["Vordere Schulter", "Hintere Schulter"], typ: "Iso" },
  { n: "KH Aufrechtes Rudern", haupt: "Seitliche Schulter", neben: ["Oberer Rücken", "Bizeps"], typ: "Comp" },
  { n: "KH Nubret Seitheben, liegend", haupt: "Seitliche Schulter", neben: [], typ: "Iso" },
  { n: "KH Seitheben", haupt: "Seitliche Schulter", neben: ["Vordere Schulter", "Hintere Schulter"], typ: "Iso" },
  { n: "LH Aufrechtes Rudern", haupt: "Seitliche Schulter", neben: ["Oberer Rücken", "Bizeps"], typ: "Comp" },
  { n: "LH Nackendrücken", haupt: "Seitliche Schulter", neben: ["Vordere Schulter", "Trizeps", "Oberer Rücken"], typ: "Comp" },
  { n: "Multipresse Aufrechtes Rudern", haupt: "Seitliche Schulter", neben: ["Oberer Rücken", "Bizeps"], typ: "Comp" },
  { n: "Multipresse Nackendrücken", haupt: "Seitliche Schulter", neben: ["Vordere Schulter", "Trizeps", "Oberer Rücken"], typ: "Comp" },
  { n: "PlateLoaded Nackendrücken", haupt: "Seitliche Schulter", neben: ["Vordere Schulter", "Trizeps", "Oberer Rücken"], typ: "Comp" },
  { n: "PlateLoaded Seitheben", haupt: "Seitliche Schulter", neben: ["Vordere Schulter", "Hintere Schulter"], typ: "Iso" },
  { n: "Steck Nackendrücken", haupt: "Seitliche Schulter", neben: ["Vordere Schulter", "Trizeps", "Oberer Rücken"], typ: "Comp" },
  { n: "Steck Seitheben", haupt: "Seitliche Schulter", neben: ["Vordere Schulter", "Hintere Schulter"], typ: "Iso" },
  { n: "SZ Aufrechtes Rudern", haupt: "Seitliche Schulter", neben: ["Oberer Rücken", "Bizeps"], typ: "Comp" },
  { n: "Kabel Reverse Flys", haupt: "Hintere Schulter", neben: ["Oberer Rücken"], typ: "Iso" },
  { n: "Kabel Seitheben, vorgebeugt", haupt: "Hintere Schulter", neben: ["Oberer Rücken"], typ: "Iso" },
  { n: "KH Reverse Flys", haupt: "Hintere Schulter", neben: ["Oberer Rücken"], typ: "Iso" },
  { n: "KH Seitheben, vorgebeugt", haupt: "Hintere Schulter", neben: ["Oberer Rücken"], typ: "Iso" },
  { n: "Rear Delt Rows", haupt: "Hintere Schulter", neben: ["Oberer Rücken"], typ: "Iso" },
  { n: "PlateLoaded Reverse Flys", haupt: "Hintere Schulter", neben: ["Oberer Rücken"], typ: "Iso" },
  { n: "Steck Reverse Flys", haupt: "Hintere Schulter", neben: ["Oberer Rücken"], typ: "Iso" },
  { n: "Kabel Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "Kabel Schrägbank Spider Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "Kabel Scott Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "Kabel Superman-Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "KH Commerfordcurls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "KH Curls, alternierend, rotierend", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "KH Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "KH Hammercurls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "KH Konzentrationscurls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "KH Schrägbank Spider Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "KH Schrägbankcurls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "KH Scott Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "LH Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "LH Schrägbank Spider Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "LH Scott Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "PlateLoaded Scott Curls, Maschine", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "Steck Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "Steck Scott Curls, Maschine", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "SZ Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "SZ Schrägbank Spider Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "SZ Scott Curls", haupt: "Bizeps", neben: ["Unterarme"], typ: "Iso" },
  { n: "Bankdips", haupt: "Trizeps", neben: ["Brust", "Vordere Schulter"], typ: "Comp" },
  { n: "Kabel Dips (Trizepsbetont)", haupt: "Trizeps", neben: ["Brust", "Vordere Schulter"], typ: "Comp" },
  { n: "Kabel Frenchpress", haupt: "Trizeps", neben: [], typ: "Iso" },
  { n: "Kabel Trizepsstrecken", haupt: "Trizeps", neben: [], typ: "Iso" },
  { n: "KH Kickbacks", haupt: "Trizeps", neben: [], typ: "Iso" },
  { n: "KH Trizepsstrecken, liegend", haupt: "Trizeps", neben: [], typ: "Iso" },
  { n: "KH Trizepsstrecken, Überkopf", haupt: "Trizeps", neben: [], typ: "Iso" },
  { n: "LH Frenchpress", haupt: "Trizeps", neben: [], typ: "Iso" },
  { n: "LH Trizepsstrecken, Überkopf", haupt: "Trizeps", neben: [], typ: "Iso" },
  { n: "PlateLoaded Dips (Trizepsbetont)", haupt: "Trizeps", neben: ["Brust", "Vordere Schulter"], typ: "Comp" },
  { n: "Steck Dips (Trizepsbetont)", haupt: "Trizeps", neben: ["Brust", "Vordere Schulter"], typ: "Comp" },
  { n: "SZ JM Press", haupt: "Trizeps", neben: [], typ: "Iso" },
  { n: "SZ Frenchpress", haupt: "Trizeps", neben: [], typ: "Iso" },
  { n: "SZ Trizepsstrecken, Überkopf", haupt: "Trizeps", neben: [], typ: "Iso" },
  { n: "Deadhang", haupt: "Unterarme", neben: [], typ: "Iso" },
  { n: "Kabel Reverse Curls", haupt: "Unterarme", neben: ["Bizeps"], typ: "Iso" },
  { n: "Kabel Reverse Unterarmcurls (Extension)", haupt: "Unterarme", neben: [], typ: "Iso" },
  { n: "Kabel Unterarmcurls (Flexion)", haupt: "Unterarme", neben: [], typ: "Iso" },
  { n: "KH Unterarmcurls (Flexion)", haupt: "Unterarme", neben: [], typ: "Iso" },
  { n: "KH Zottman Curls", haupt: "Unterarme", neben: ["Bizeps"], typ: "Iso" },
  { n: "LH Reverse Curls", haupt: "Unterarme", neben: ["Bizeps"], typ: "Iso" },
  { n: "LH Reverse Unterarmcurls (Extension)", haupt: "Unterarme", neben: [], typ: "Iso" },
  { n: "LH Unterarmcurls (Flexion)", haupt: "Unterarme", neben: [], typ: "Iso" },
  { n: "LH/KH Heben Fatgripz", haupt: "Unterarme", neben: [], typ: "Iso" },
  { n: "Scheiben Heben", haupt: "Unterarme", neben: [], typ: "Iso" },
  { n: "SZ Reverse Curls", haupt: "Unterarme", neben: ["Bizeps"], typ: "Iso" },
  { n: "KH Ausfallschritte", haupt: "Quads", neben: ["Glutes", "Abduktoren"], typ: "Comp" },
  { n: "KH Bulgarian Splitsquats", haupt: "Quads", neben: ["Glutes", "Abduktoren"], typ: "Comp" },
  { n: "KH/Kettlebell Goblet Squats", haupt: "Quads", neben: ["Glutes", "Abduktoren", "Hams"], typ: "Comp" },
  { n: "KH StepUps", haupt: "Quads", neben: ["Glutes", "Abduktoren", "Hams"], typ: "Comp" },
  { n: "LH StepUps", haupt: "Quads", neben: ["Glutes", "Abduktoren", "Hams"], typ: "Comp" },
  { n: "LH Ausfallschritte", haupt: "Quads", neben: ["Glutes", "Abduktoren"], typ: "Comp" },
  { n: "LH Bulgarian Splitsquats", haupt: "Quads", neben: ["Glutes", "Abduktoren"], typ: "Comp" },
  { n: "LH Frontkniebeugen", haupt: "Quads", neben: ["Glutes"], typ: "Comp" },
  { n: "LH Kniebeugen", haupt: "Quads", neben: ["Glutes", "Abduktoren", "Hams"], typ: "Comp" },
  { n: "Belt Squats", haupt: "Quads", neben: ["Glutes", "Abduktoren", "Hams"], typ: "Comp" },
  { n: "Multipresse Frontkniebeugen", haupt: "Quads", neben: ["Glutes"], typ: "Comp" },
  { n: "Multipresse Kniebeugen", haupt: "Quads", neben: ["Glutes", "Abduktoren", "Hams"], typ: "Comp" },
  { n: "Multipresse Ausfallschritte", haupt: "Quads", neben: ["Glutes", "Abduktoren", "Hams"], typ: "Comp" },
  { n: "PlateLoaded Beinpresse", haupt: "Quads", neben: ["Glutes", "Abduktoren", "Hams"], typ: "Comp" },
  { n: "PlateLoaded Beinstrecken", haupt: "Quads", neben: [], typ: "Iso" },
  { n: "PlateLoaded Hackenschmidt", haupt: "Quads", neben: ["Glutes", "Abduktoren", "Hams"], typ: "Comp" },
  { n: "Pendulum Squats", haupt: "Quads", neben: ["Glutes", "Abduktoren", "Hams"], typ: "Comp" },
  { n: "Steck Beinpresse", haupt: "Quads", neben: ["Glutes", "Abduktoren", "Hams"], typ: "Comp" },
  { n: "Steck Beinstrecken", haupt: "Quads", neben: [], typ: "Iso" },
  { n: "KH Deadlifts (konventionell)", haupt: "Hams", neben: ["Glutes", "Quads"], typ: "Comp" },
  { n: "KH RDL (Rumänisches Kreuzheben)", haupt: "Hams", neben: ["Glutes"], typ: "Comp" },
  { n: "LH Deadlifts (konventionell)", haupt: "Hams", neben: ["Glutes", "Quads"], typ: "Comp" },
  { n: "LH Good Mornings", haupt: "Hams", neben: ["Glutes"], typ: "Comp" },
  { n: "LH RDL (Rumänisches Kreuzheben)", haupt: "Hams", neben: ["Glutes"], typ: "Comp" },
  { n: "Glute Ham Raises", haupt: "Hams", neben: ["Glutes"], typ: "Comp" },
  { n: "Multipresse RDL (Rumänisches Kreuzheben)", haupt: "Hams", neben: ["Glutes"], typ: "Comp" },
  { n: "Nordic Hamstring Curls", haupt: "Hams", neben: ["Glutes"], typ: "Iso" },
  { n: "PlateLoaded Beinbeugen, liegend", haupt: "Hams", neben: ["Waden"], typ: "Iso" },
  { n: "PlateLoaded Beinbeugen, sitzend", haupt: "Hams", neben: ["Waden"], typ: "Iso" },
  { n: "PlateLoaded Beinbeugen, stehend", haupt: "Hams", neben: ["Waden"], typ: "Iso" },
  { n: "Steck Beinbeugen, liegend", haupt: "Hams", neben: ["Waden"], typ: "Iso" },
  { n: "Steck Beinbeugen, sitzend", haupt: "Hams", neben: ["Waden"], typ: "Iso" },
  { n: "Steck Beinbeugen, stehend", haupt: "Hams", neben: ["Waden"], typ: "Iso" },
  { n: "Kabel Kickbacks", haupt: "Glutes", neben: ["Hams"], typ: "Iso" },
  { n: "Kabel Pull-Througs", haupt: "Glutes", neben: ["Hams"], typ: "Iso" },
  { n: "KH Back Extensions", haupt: "Glutes", neben: ["Hams"], typ: "Iso" },
  { n: "LH Back Extensions", haupt: "Glutes", neben: ["Hams"], typ: "Iso" },
  { n: "LH Hip Thrust", haupt: "Glutes", neben: ["Hams"], typ: "Comp" },
  { n: "LH Sumo-Deadlifts", haupt: "Glutes", neben: ["Abduktoren", "Quads", "Hams"], typ: "Comp" },
  { n: "LH Trap-Bar Deadlifts", haupt: "Glutes", neben: ["Quads", "Hams"], typ: "Comp" },
  { n: "Multipresse Hip Thrust", haupt: "Glutes", neben: ["Hams"], typ: "Comp" },
  { n: "PlateLoaded Abduktionen", haupt: "Glutes", neben: [], typ: "Iso" },
  { n: "PlateLoaded Hip Thrust", haupt: "Glutes", neben: ["Hams"], typ: "Comp" },
  { n: "Steck Abduktionen", haupt: "Glutes", neben: [], typ: "Iso" },
  { n: "PlateLoaded Abduktionen (seitlich)", haupt: "Abduktoren", neben: [], typ: "Iso" },
  { n: "Kabel Abduktionen", haupt: "Abduktoren", neben: [], typ: "Iso" },
  { n: "Steck Abduktionen (seitlich)", haupt: "Abduktoren", neben: [], typ: "Iso" },
  { n: "KH Wadenheben, stehend", haupt: "Waden", neben: [], typ: "Iso" },
  { n: "LH Wadenheben, sitzend", haupt: "Waden", neben: [], typ: "Iso" },
  { n: "LH Wadenheben, stehend", haupt: "Waden", neben: [], typ: "Iso" },
  { n: "Multipresse Wadenheben, sitzend", haupt: "Waden", neben: [], typ: "Iso" },
  { n: "Multipresse Wadenheben, stehend", haupt: "Waden", neben: [], typ: "Iso" },
  { n: "PlateLoaded Wadenheben, sitzend", haupt: "Waden", neben: [], typ: "Iso" },
  { n: "PlateLoaded Wadenheben, stehend", haupt: "Waden", neben: [], typ: "Iso" },
  { n: "Donkeywadenheben", haupt: "Waden", neben: [], typ: "Iso" },
  { n: "Steck Wadenheben, sitzend", haupt: "Waden", neben: [], typ: "Iso" },
  { n: "Steck Wadenheben, stehend", haupt: "Waden", neben: [], typ: "Iso" },
  { n: "Liegendes Beinheben", haupt: "Abs", neben: [], typ: "Iso" },
  { n: "Ab-Rollouts", haupt: "Abs", neben: [], typ: "Iso" },
  { n: "Pallof Press", haupt: "Abs", neben: [], typ: "Iso" },
  { n: "Reverse Crunches", haupt: "Abs", neben: [], typ: "Iso" },
  { n: "Kabel Woodchopper", haupt: "Abs", neben: [], typ: "Iso" },
  { n: "Hollow Body Holds", haupt: "Abs", neben: [], typ: "Iso" },
  { n: "Hängendes Beinheben", haupt: "Abs", neben: [], typ: "Iso" },
  { n: "Kabel Crunches", haupt: "Abs", neben: [], typ: "Iso" },
  { n: "Planks", haupt: "Abs", neben: [], typ: "Iso" },
  { n: "Sideplanks", haupt: "Abs", neben: [], typ: "Iso" },
];
