#!/usr/bin/env python3
"""Build the small, deployable text corpus used by the Coach edge function.

PDFs are converted page-by-page so file_search can return the original title
and the model can name a page. Excel formulas are deliberately excluded: the
authoritative implementation remains in src/ypsiFormel.js.
"""

import hashlib
import json
from pathlib import Path

from pypdf import PdfReader

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "supabase/functions/capboy-coach/knowledge.ts"


def clean(text: str) -> str:
    return "\n".join(line.rstrip() for line in text.replace("\x00", "").splitlines()).strip()


sources = []
parts = []
documents = []
for path in sorted((ROOT / "Seminarunterlagen").rglob("*.pdf")):
    reader = PdfReader(str(path))
    rel = path.relative_to(ROOT / "Seminarunterlagen").as_posix()
    pages = []
    for index, page in enumerate(reader.pages, 1):
        text = clean(page.extract_text() or "")
        if text:
            pages.append(f"## Seite {index}\n{text}")
    document = f"# Quelle: {rel}\n\n" + "\n\n".join(pages)
    parts.append(document)
    safe_name = rel.replace("/", " - ") + ".txt"
    documents.append({"title": path.stem, "filename": safe_name, "content": document})
    sources.append({"title": path.stem, "filename": safe_name, "original": rel, "pages": len(reader.pages), "kind": "pdf"})

for filename, title in [
    ("src/data/hautfalten-faktoren.json", "Strukturierte Hautfalten-Gegenprüfungen"),
    ("src/data/hautfalten.json", "Strukturierte Hautfalten-Erklärungen"),
    ("src/data/ypsi-protokolle.json", "Strukturierte Seminar-Protokolle"),
]:
    path = ROOT / filename
    payload = json.loads(path.read_text(encoding="utf-8"))
    document = f"# Quelle: {title}\n\n```json\n{json.dumps(payload, ensure_ascii=False, indent=2)}\n```"
    safe_name = Path(filename).name + ".txt"
    parts.append(document)
    documents.append({"title": title, "filename": safe_name, "content": document})
    sources.append({"title": title, "filename": safe_name, "original": filename, "pages": None, "kind": "structured"})

formula = json.loads((ROOT / "src/data/ypsi-formel.json").read_text(encoding="utf-8"))
corpus = "\n\n---\n\n".join(parts)
content_hash = hashlib.sha256(corpus.encode("utf-8")).hexdigest()

header = "// Generated by scripts/generate-coach-knowledge.py. Do not edit by hand.\n"
output = header + "export const KNOWLEDGE_VERSION = " + json.dumps(content_hash) + ";\n"
output += "export const KNOWLEDGE_FILENAME = 'CAPBOY-Seminarwissen.md';\n"
output += "export const KNOWLEDGE_SOURCES = " + json.dumps(sources, ensure_ascii=False, indent=2) + " as const;\n"
output += "export const KNOWLEDGE_DOCUMENTS = " + json.dumps(documents, ensure_ascii=False) + " as const;\n"
output += "export const YPSI_FORMULA = " + json.dumps(formula, ensure_ascii=False, indent=2) + " as const;\n"
output += "export const SEMINAR_KNOWLEDGE = " + json.dumps(corpus, ensure_ascii=False) + ";\n"
OUTPUT.write_text(output, encoding="utf-8")
print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(corpus):,} chars, {len(sources)} sources, {content_hash[:12]})")
